/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAdminButton: typeof import('./src/components/AddAdminButton.vue')['default']
    AddTaskButton: typeof import('./src/components/AddTaskButton.vue')['default']
    AdminRegister: typeof import('./src/components/AdminRegister.vue')['default']
    AdminRegisterForm: typeof import('./src/components/AdminRegisterForm.vue')['default']
    Clipboard: typeof import('./src/components/Clipboard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    FormItem: typeof import('./src/components/FormItem.vue')['default']
    InitialChatWindow: typeof import('./src/components/InitialChatWindow.vue')['default']
    LoadingEffect: typeof import('./src/components/LoadingEffect.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    MessageContent: typeof import('./src/components/MessageContent.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    MobileMenu: typeof import('./src/components/MobileMenu.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutineDialog: typeof import('./src/components/RoutineDialog.vue')['default']
    RoutineEdit: typeof import('./src/components/RoutineEdit.vue')['default']
    RoutineList: typeof import('./src/components/RoutineList.vue')['default']
    RoutineTags: typeof import('./src/components/RoutineTags.vue')['default']
    TaskForm: typeof import('./src/components/TaskForm.vue')['default']
    TaskTags: typeof import('./src/components/TaskTags.vue')['default']
    TinyMap: typeof import('./src/components/TinyMap.vue')['default']
    UserRandomTask: typeof import('./src/components/UserRandomTask.vue')['default']
  }
}
