/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    FormInput: typeof import('./src/components/FormInput.vue')['default']
    FormItem: typeof import('./src/components/FormItem.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TipsMessage: typeof import('./src/components/TipsMessage.vue')['default']
  }
}
